---
title: "Why useSuspenseQuery works"
description: "A reader asked 'Wtf why does this work?'"
published: 2024-05-30
categories: "React, React Query, Suspense, Reader Question"
hero: ./img/screenshot-1717082698450.png
---

Fellow reader Michael had a great question about [yesterday's email](https://swizec.com/blog/cleaner-components-with-use-suspense-query/) â€“ Why does this work!?

> How does the Birthdays component use the return value from `useBirths` before the request is complete? Is it an empty array at first, and if so how? `births.map` is called below, so we assume it's an array at the point of first render.

Here's [the code again](https://github.com/Swizec/suspense-example/blob/main/src/WikipediaBirthdays.tsx#L65):

```typescript
const Birthdays: FC<{ day: Date }> = ({ day }) => {
  const births = useBirths(day)

  return <Table data-testid="birthday-list">
	  <tbody>
        {births.map((birth, index) => ( //...
  </Table>
}
```

Why can we call `births.map` and assume it's an array?

That's the clever trick behind React Suspense â€“Â in JavaScript **you can throw a promise**.

You've seen `throw new Error()` before. That lets you stop execution of your code when there's a problem and jump into the `catch` block of a try/catch.

But you don't _have to_ throw an error. You could throw a different object and give it special behavior in the catch block. That's what React does with Suspense â€“ it catches unresolved promises thrown from your component tree then comes back to finish rendering when the promise resolves.

That means somewhere inside `useSuspenseQuery` there will be code that throws your `queryFn`. Let's see ...

Yep, [here it is](https://github.com/TanStack/query/blob/main/packages/react-query/src/useBaseQuery.ts#L98)

```typescript
// Handle suspense
if (shouldSuspend(defaultedOptions, result)) {
  // Do the same thing as the effect right above because the effect won't run
  // when we suspend but also, the component won't re-mount so our observer would
  // be out of date.
  throw fetchOptimistic(defaultedOptions, observer, errorResetBoundary)
}
```

If we're using suspense, _throw_ the promise returned by fetch.

Brilliant ðŸ¤©

~Swizec
